---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      # Needed to invoke the local action
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Move local repository pre-commit file'
        shell: bash
        run: |
          # Move local repository pre-commit file
          mv .pre-commit-config.yaml /tmp
          # Checkout a branch to pass that linting test
          git checkout -b linting-test-branch

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          # No need to checkout the local repository twice
          no_checkout: true

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'lfreleng-actions/test-python-project'
          path: 'test-python-project'

      - name: 'Checkout a branch prior to running linting'
        shell: bash
        run: |
          # Checkout a branch prior to running linting
          cd test-python-project
          git checkout -b linting-test-branch

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [test-python-project]"
        uses: ./
        with:
          # No need to checkout the local repository twice
          no_checkout: true
          path_prefix: 'test-python-project'

      - name: "Running local action: ${{ github.repository }} [invalid-path]"
        id: failure
        uses: ./
        with:
          # No need to checkout the local repository twice
          no_checkout: true
          path_prefix: 'invalid-path'
        # Deliberate test failure
        continue-on-error: true

      - name: 'Error if step above did NOT fail'
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo 'Error: previous test step did NOT fail ❌'
          exit 1
